// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1sUdmDFGS4xMsLtc7dGgkg5y4MlSutSY',
    appId: '1:443633037277:web:e926a7ea618df399f3d034',
    messagingSenderId: '443633037277',
    projectId: 'startupsandfunds',
    authDomain: 'startupsandfunds.firebaseapp.com',
    databaseURL: 'https://startupsandfunds-default-rtdb.firebaseio.com',
    storageBucket: 'startupsandfunds.appspot.com',
    measurementId: 'G-EE9QNMVGQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIPN-bbxzFQSUUjNaT_BQcHNU0tum1d98',
    appId: '1:443633037277:android:13ad272357c2c70ef3d034',
    messagingSenderId: '443633037277',
    projectId: 'startupsandfunds',
    databaseURL: 'https://startupsandfunds-default-rtdb.firebaseio.com',
    storageBucket: 'startupsandfunds.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRoahb2Q2C_GGOLeGYiBzu1B3TgqEowPw',
    appId: '1:443633037277:ios:54a50a8f4fc9f4dbf3d034',
    messagingSenderId: '443633037277',
    projectId: 'startupsandfunds',
    databaseURL: 'https://startupsandfunds-default-rtdb.firebaseio.com',
    storageBucket: 'startupsandfunds.appspot.com',
    androidClientId: '443633037277-5v1st2v6771s5s3gp1io7rtqr8duhu5c.apps.googleusercontent.com',
    iosClientId: '443633037277-4kickpt54qfk68nbd42m3bgbgtlerem7.apps.googleusercontent.com',
    iosBundleId: 'com.bos.startupandfunds.startupandfunds',
  );
}
